apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-configmap
data:
  servers.json: |
    {
        "Servers": {
            "1": {
                "Name": "application",
                "Group": "Servers",
                "Host": "mypg-yc-pooler.mypg.svc.cluster.local",
                "Port": 5432,
                "MaintenanceDB": "myappdb",
                "Username": "myappuser2",
                "UseSSHTunnel": 0,
                "TunnelPort": "22",
                "TunnelAuthentication": 0,
                "KerberosAuthentication": false,
                "ConnectionParameters": {
                    "sslmode": "prefer",
                    "connect_timeout": 10
                }
            },
            "2": {
                "Name": "read-only",
                "Group": "Servers",
                "Host": "mypg-yc-pooler.mypg.svc.cluster.local",
                "Port": 5432,
                "MaintenanceDB": "myappdb",
                "Username": "reader",
                "UseSSHTunnel": 0,
                "TunnelPort": "22",
                "TunnelAuthentication": 0,
                "KerberosAuthentication": false,
                "ConnectionParameters": {
                    "sslmode": "prefer",
                    "connect_timeout": 10
                }
            }
        }
    }

