apiVersion: v1
data:
  username: bXlhcHB1c2Vy # echo -n 'myappuser' | base64 -w 0
  password: cGFzc3dvcmQ= # echo -n 'password' | base64 -w 0
kind: Secret
metadata:
  name: application-user-secret
type: kubernetes.io/basic-auth

