# openssl genrsa -out tls.key 4096
# openssl req -x509 -new -nodes -key tls.key -sha256 -days 7305 -out tls.crt
# (Subject: C = RU, ST = Lyubertsy, L = Lyubertsy, O = "Damage, Inc.", CN = myca)
# openssl x509 -in tls.crt -text
# cat tls.crt | base64 -w0
# cat tls.key | base64 -w0
# echo -n 'base64_cert' | base64 -d | openssl x509 -text
---
apiVersion: v1
kind: Secret
metadata:
  name: myca-key-pair
  namespace: cert-manager
data:
  tls.crt: ABCDEFGH
  tls.key: IJKLMNOPQRSTUVWX
