apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
type: Opaque
data:
  PGADMIN_DEFAULT_EMAIL: "dXNlckBkb21haW4uY29t" # echo -n 'user@domain.com' | base64 -w 0
  PGADMIN_DEFAULT_PASSWORD: "cGFzc3dvcmQ=" # echo -n 'password' | base64 -w 0

