apiVersion: v1
kind: Secret
metadata:
  name: post-sql-secret
type: Opaque
stringData:
  post-sql-secret.sql: |
    create user myappuser2 with encrypted password 'password';
    grant connect, create on database myappdb to myappuser2;
    grant pg_read_all_data, pg_read_all_settings to myappuser2;
    grant pg_write_all_data to myappuser2;
    create schema if not exists myapp authorization myappuser;
    grant usage, create on schema myapp to myappuser2;
    create user reader with encrypted password 'password';
    grant connect on database myappdb to reader;
    grant pg_read_all_data, pg_read_all_settings to reader;

