# yc iam access-key create --service-account-name my-backup-sa --description "Key for S3"
apiVersion: v1
kind: Secret
metadata:
  name: mypg-yc-s3-secret
type: Opaque
data:
  ACCESS_KEY_ID: "a2V5X2lk" # echo -n 'key_id' | base64 -w 0
  ACCESS_SECRET_KEY: "c2VjcmV0" # echo -n 'secret' | base64 -w 0

