apiVersion: v1
kind: Service
metadata:
  name: mypg-yc-svc-lb
spec:
  type: LoadBalancer
  ports:
  - name: postgres
    port: 5433
    protocol: TCP
    targetPort: 5432
    nodePort: 30433
  selector:
    cnpg.io/cluster: mypg-yc
    role: primary
