apiVersion: v1
kind: Service
metadata:
  name: mypg-yc-pooler-svc-lb
spec:
  type: LoadBalancer
  ports:
  - name: postgres
    port: 6543
    protocol: TCP
    targetPort: 5432
    nodePort: 30543
  selector:
    cnpg.io/cluster: mypg-yc
    cnpg.io/podRole: pooler
    cnpg.io/poolerName: mypg-yc-pooler

