apiVersion: v1
kind: Service
metadata:
  name: mypg-svc-lb
spec:
  type: LoadBalancer
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: 5432
    nodePort: 30432
  selector:
    cnpg.io/cluster: mypg
    role: primary
