# kubectl create secret generic mypg-s3-secret --from-literal=ACCESS_KEY_ID='mypguser' --from-literal=ACCESS_SECRET_KEY='MyPGUserSecretKey123'
apiVersion: v1
kind: Secret
metadata:
  name: mypg-s3-secret
type: Opaque
data:
  ACCESS_KEY_ID: "bXlwZ3VzZXI=" # echo -n 'mypguser' | base64 -w 0
  ACCESS_SECRET_KEY: "TXlQR1VzZXJTZWNyZXRLZXkxMjM=" # echo -n 'MyPGUserSecretKey123' | base64 -w 0

