apiVersion: v1
kind: Service
metadata:
  name: pgadmin-svc-lb
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30800
  selector:
    app: pgadmin

