apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-configmap
data:
  servers.json: |
    {
        "Servers": {
            "1": {
                "Name": "mypg-yc-svc-lb",
                "Group": "Servers",
                "Host": "mypg-yc-svc-lb",
                "Port": 5433,
                "MaintenanceDB": "myappdb",
                "Username": "postgres",
                "UseSSHTunnel": 0,
                "TunnelPort": "22",
                "TunnelAuthentication": 0,
                "KerberosAuthentication": false,
                "ConnectionParameters": {
                    "sslmode": "prefer",
                    "connect_timeout": 10
                }
            },
            "2": {
                "Name": "mypg-yc-pooler-svc-lb",
                "Group": "Servers",
                "Host": "mypg-yc-pooler-svc-lb",
                "Port": 6543,
                "MaintenanceDB": "myappdb",
                "Username": "myappuser",
                "UseSSHTunnel": 0,
                "TunnelPort": "22",
                "TunnelAuthentication": 0,
                "KerberosAuthentication": false,
                "ConnectionParameters": {
                    "sslmode": "prefer",
                    "connect_timeout": 10
                }
            }
        }
    }

