apiVersion: v1
kind: Service
metadata:
  name: test-stand-yc-svc-lb
spec:
  type: LoadBalancer
  ports:
  - name: postgres
    port: 5435
    protocol: TCP
    targetPort: 5432
    nodePort: 30435
  selector:
    cnpg.io/cluster: test-stand-yc
    role: primary
