{{- if .Values.servicelb_on }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.servicelb.metadata.name }}
spec:
  type: LoadBalancer
  ports:
  - name: postgres
    port: {{ .Values.servicelb.spec.port }}
    protocol: TCP
    targetPort: 5432
  selector:
    cnpg.io/cluster: {{ .Values.pooler.spec.cluster.name }}
    cnpg.io/podRole: pooler
    cnpg.io/poolerName: {{ .Values.pooler.metadata.name }}
{{- end }}

