{{- if .Values.pooler.spec.pgbouncer.owncertificates_on }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.pooler.spec.pgbouncer.authquerysecret.name }}
  labels:
    cnpg.io/reload: ""
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.pooler.spec.pgbouncer.authquerysecret.name }}
spec:
  secretName: {{ .Values.pooler.spec.pgbouncer.authquerysecret.name }}
  usages:
    - client auth
  commonName: cnpg_pooler_pgbouncer
  issuerRef:
    name: {{ .Values.caclusterissuer }}
    kind: ClusterIssuer
    group: cert-manager.io
{{- end }}

