---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cladmsa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cladmsa-cluster-admin-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: cladmsa
  namespace: default
---
apiVersion: v1
kind: Secret
metadata:
  name: cladmsa-token
  namespace: default
  annotations:
    kubernetes.io/service-account.name: cladmsa
type: kubernetes.io/service-account-token
# View token:
# kubectl describe -n default secrets/cladmsa-token
# or:
# kubectl -n default get secret/cladmsa-token -o jsonpath='{.data.token}' | base64 --decode

