{{- if .Values.cluster.spec.owncertificates_on }}
# Connection to leader, examples:
# psql 'host=<your-cluster>-rw port=5432 dbname=postgres sslmode=verify-full user=streaming_replica sslrootcert=/controller/certificates/client-ca.crt sslcert=/controller/certificates/streaming_replica.crt sslkey=/controller/certificates/streaming_replica.key'
# psql 'host=<your-cluster>-rw port=5432 dbname=postgres sslmode=verify-full user=streaming_replica sslrootcert=/controller/certificates/server-ca.crt sslcert=/controller/certificates/streaming_replica.crt sslkey=/controller/certificates/streaming_replica.key'
# Connection to replica, examples:
# psql 'host=<your-cluster>-ro port=5432 dbname=postgres sslmode=verify-full user=streaming_replica sslrootcert=/controller/certificates/client-ca.crt sslcert=/controller/certificates/streaming_replica.crt sslkey=/controller/certificates/streaming_replica.key'
# psql 'host=<your-cluster>-ro port=5432 dbname=postgres sslmode=verify-full user=streaming_replica sslrootcert=/controller/certificates/server-ca.crt sslcert=/controller/certificates/streaming_replica.crt sslkey=/controller/certificates/streaming_replica.key'
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cluster.spec.certificates.servertlssecret }}
  labels:
    cnpg.io/reload: ""
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.cluster.spec.certificates.servertlssecret }}
spec:
  secretName: {{ .Values.cluster.spec.certificates.servertlssecret }}
  usages:
    - server auth
  dnsNames:
    - {{ .Values.servicelb.metadata.name }}
    - {{ .Values.servicelb.metadata.name }}.{{ .Values.namespace }}
    - {{ .Values.servicelb.metadata.name }}.{{ .Values.namespace }}.svc
    - {{ .Values.servicelb.metadata.name }}.{{ .Values.namespace }}.svc.cluster.local
    - {{ .Values.cluster.metadata.name }}-rw
    - {{ .Values.cluster.metadata.name }}-rw.{{ .Values.namespace }}
    - {{ .Values.cluster.metadata.name }}-rw.{{ .Values.namespace }}.svc
    - {{ .Values.cluster.metadata.name }}-rw.{{ .Values.namespace }}.svc.cluster.local
    - {{ .Values.cluster.metadata.name }}-r
    - {{ .Values.cluster.metadata.name }}-r.{{ .Values.namespace }}
    - {{ .Values.cluster.metadata.name }}-r.{{ .Values.namespace }}.svc
    - {{ .Values.cluster.metadata.name }}-r.{{ .Values.namespace }}.svc.cluster.local
    - {{ .Values.cluster.metadata.name }}-ro
    - {{ .Values.cluster.metadata.name }}-ro.{{ .Values.namespace }}
    - {{ .Values.cluster.metadata.name }}-ro.{{ .Values.namespace }}.svc
    - {{ .Values.cluster.metadata.name }}-ro.{{ .Values.namespace }}.svc.cluster.local
  issuerRef:
    name: {{ .Values.caclusterissuer }}
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cluster.spec.certificates.replicationtlssecret }}
  labels:
    cnpg.io/reload: ""
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.cluster.spec.certificates.replicationtlssecret }}
spec:
  secretName: {{ .Values.cluster.spec.certificates.replicationtlssecret }}
  usages:
    - client auth
  commonName: streaming_replica
  issuerRef:
    name: {{ .Values.caclusterissuer }}
    kind: ClusterIssuer
    group: cert-manager.io
{{- end }}

