# Example 1 (without definde host)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.deployment.metadata.name }}-ingress1
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    cert-manager.io/cluster-issuer: "{{ .Values.clusterissuer }}"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /web/(.*)
        # There are:
        # /web/
        # /web/index.html
        # /web/kitty.html
        # /web/basic_status      
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Values.service.metadata.name }}
            port:
              number: {{ .Values.port }}
      - path: /main
        # There is main page only (on /main)
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.service.metadata.name }}
            port:
              number: {{ .Values.port }}
    #host: "{{ .Values.inclbip }}.nip.io"
  tls:
  - secretName: {{ .Values.tls.secret }}
    hosts:
    - {{ .Values.inclbip }}
    - {{ .Values.inclbip }}.nip.io
    - web.{{ .Values.inclbip }}.nip.io
    - pgadmin.{{ .Values.inclbip }}.nip.io
    - grafana.{{ .Values.inclbip }}.nip.io

# Show:
# curl -kv https://{{ .Values.inclbip }}/web/

