apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.metadata.name }}
spec:
  selector:
    app: {{ .Values.deployment.metadata.name }}
  type: ClusterIP
  clusterIP: None
  ports:
    - protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.targetport }}

